apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  scaleTargetRef:
    kind: ReplicationController
    name: php-apache
  minReplicas: 1
  maxReplicas: 10

